### ISSUE TITLE
Discussion detail> comment > Post a comment function working as comment reply

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#100]
**Describe the bug**
Not able to add another comment in the comment section, it's working as reply on the same comment.

![image](https://user-images.githubusercontent.com/109590553/198956184-92795d49-89a7-4b4b-bb58-9d0a47577279.png)

**Comment by technicalbirdVayuz** [comment]
will discuss

**Comment by technicalbirdVayuz** [comment]
Scroll needs to be added when reply gets posted
