### ISSUE TITLE
Group detail> wrong member left the group

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#101]
**Describe the bug**
Anupriya left the group, but ankit arora's profile got removed. 

**To Reproduce**
1. Go to 'group listing'
2. Click on 'group detail'
3. Scroll down to '3 dots, leave group'

**Screenshots**
![image](https://user-images.githubusercontent.com/109590553/198957128-e928fdb8-49f8-4390-b190-427742cdd46a.png)

**Comment by technicalbirdVayuz** [comment]
Related with #99
