### ISSUE TITLE
Discussion detail> add tool tip for reply icon

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#105]
![image](https://user-images.githubusercontent.com/109590553/198960907-b0399bf7-5f72-49b6-a06d-f5bf88a10e79.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/201837895-9b720cb7-ab96-4ae8-9b34-f83a5a28e152.png)

**Comment by technicalbirdVayuz** [comment]
Added
