### ISSUE TITLE
Groups listing> Remove the highlight on 3 dots

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#107]
![image](https://user-images.githubusercontent.com/109590553/199424071-5143b3db-007c-4bc3-a9ed-8cf5e216fceb.png)

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger That will probably stay there as group banner can have any form of color and the 3 dots only can either be white or black , so to differentiate it in order to not let it mix with any color pattern of group banners I had added bg there

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar Put 3 dots below the image.
Use Social events reference: 
![image](https://user-images.githubusercontent.com/109590553/199438539-35a6c28c-567f-4422-880c-1d90bec57b2b.png)
