### ISSUE TITLE
Create group> user name profile UI not correct

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#109]
![image](https://user-images.githubusercontent.com/109590553/199425885-0b3921dd-ddd5-4398-b855-a7cdc639ee9d.png)

**Comment by bidyut-majumdar** [comment]
![2022-11-02_130423](https://user-images.githubusercontent.com/78781245/199427437-375c5522-fde5-4fe1-a3fb-a9b5efbce0fe.png)

@Anupriyabanger based on UI perspective the UI doesn't have any issue currently .

**Comment by bidyut-majumdar** [comment]
![2022-11-02_130548](https://user-images.githubusercontent.com/78781245/199427740-045f549d-2919-4f39-8aeb-7009e5303574.png)

@technicalbirdVayuz  As you can see in the image that Achyuth Kumar doesn't have any profile pic or anything, purely going blank, so please do the needful of placing any placeholder avatar for the users not having profile pic in their profile .
