### ISSUE TITLE
Create group> Private group> Add option to invite members in 3 dots

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#110]
**Describe the bug**
While creating a private group, I have to go to edit group detail and then send invites to the users. 

![image](https://user-images.githubusercontent.com/109590553/199427709-50d23ad6-5861-4273-bd71-d2e2d8818128.png)

**Comment by technicalbirdVayuz** [comment]
Option added some use cases needs to be handled
