### ISSUE TITLE
Create Group >> In Editor  tool Tip ( number listing shows 2 times ).

### ISSUE THREAD

**Issue by harshvayuz** [Bitovn-Micro-Services/groups-issues#119]
![Screenshot 2022-11-09 at 1 48 21 PM](https://user-images.githubusercontent.com/86279887/200780866-34aec74b-4d4c-4b85-ab4f-5c41655f0be3.png)

**Comment by harshvayuz** [comment]
1. please Check Alignmnet

**Comment by technicalbirdVayuz** [comment]
Duplicate #122
