### ISSUE TITLE
Search Group members >> when ever I clear the Search it doest not show me the list of member i have to press the Enter Button to achieve 

### ISSUE THREAD

**Issue by harshvayuz** [Bitovn-Micro-Services/groups-issues#120]

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz please check this .

**Comment by technicalbirdVayuz** [comment]
Yes, this is not an issue. Its designed for bulk of Users, So Calling API is mandatory here. 

Feel free to discuss. Closing this as of now
