### ISSUE TITLE
Comments> Remove Toast msg for already vote

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#123]
1. On clicking twice vote should be removed.
![image](https://user-images.githubusercontent.com/109590553/202415588-4f93dd67-869a-47a4-a571-248ecbb1eb52.png)

**Comment by technicalbirdVayuz** [comment]
Please check with new comments

**Comment by technicalbirdVayuz** [comment]
Its configured
