### ISSUE TITLE
Listing> Add icon for public, private and open group

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#128]
![image](https://user-images.githubusercontent.com/109590553/204499966-059ca992-025e-4baa-b54e-ab4d20938d52.png)

**Comment by technicalbirdVayuz** [comment]
@bidyut-majumdar Check added from my end. Please adjust the UI

![image](https://user-images.githubusercontent.com/18699624/204785796-e5bf8de8-9a43-462c-8d2e-3c08a98beb4b.png)
