### ISSUE TITLE
Detail> comment> reaction> flags are not visible

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#137]
![image](https://user-images.githubusercontent.com/109590553/204510585-5c11ef48-a282-419d-ba9a-5c4fe1ab7296.png)

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz upon checking I found this is some sort of issue from the emoji library I believe ? Please check onto this as couldn't find my actionable here .

**Comment by technicalbirdVayuz** [comment]
Emojies has been removed, so its no longer valid
