### ISSUE TITLE
Detail> On clicking back button user should be directed to listing page 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#143]
If user is on the detail page, then on clicking back user should be directed to Listing page. Right now I have to click back multiple times to reach to listing page.

**Comment by technicalbirdVayuz** [comment]
Its working fine


https://user-images.githubusercontent.com/18699624/204786391-1ed63483-dc01-458b-b336-2e66bdfc8d3d.mp4
