### ISSUE TITLE
Listing> advance filter> No data shown on selecting just group type 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#154]
**Describe the bug**
I did not typed any group name, I just selected group type, Then no data is showing. It should show me all the public groups available on the platform. 
![image](https://user-images.githubusercontent.com/109590553/206997644-c375e868-f881-440f-a589-926450e5fe50.png)

**Comment by technicalbirdVayuz** [comment]
Its working fine
