### ISSUE TITLE
Create group> Incorrect text 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#157]
Incorrect Groups spelling 
![image](https://user-images.githubusercontent.com/109590553/207032946-caddfeb6-2f5f-4229-af31-98ff2389d652.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/223020506-50c3dd9e-f003-4922-898a-604a270b3a96.png)
