### ISSUE TITLE
Group > Suggestions > There Should be Posted Date on every group.

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#178]
![image](https://user-images.githubusercontent.com/109590553/218683781-209b821c-f500-41f4-ac25-b01928dd30ae.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/223019321-93b7bed3-0655-4287-a760-9a8621fef826.png)
Pls confirm

**Comment by Anupriyabanger** [comment]
@technicalbirdVayuz Please Add date on which the Group was created  
![image](https://user-images.githubusercontent.com/109590553/223049068-45cdbe13-7969-4afb-92ba-7d0a9c700151.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/223322286-c4cf9c88-00f7-44fb-850b-4a8eb3ee7d64.png)
