### ISSUE TITLE
Group | Change Header Text of Invites

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn-Micro-Services/groups-issues#192]
please change Invite title to Request

**Comment by Anupriyabanger** [comment]
@technicalbirdVayuz, Please change the tile Invites to requested in the Public group. 
![image](https://user-images.githubusercontent.com/109590553/223044460-c4c64d51-979a-470e-a4b7-ed55009f6e4b.png)

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/223322986-6e3c3919-5a11-4f76-a37c-58bfe6249086.png)
