### ISSUE TITLE
Cropper v2 project showing older cropper as compared to cropper modal of create group form

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#25]
Cropper v2 project showing older cropper as compared to cropper modal of create group form

![2022-09-06_131917](https://user-images.githubusercontent.com/78781245/188577644-0ddee2b8-56b6-4965-85db-7c84a4b06355.png)

**Comment by technicalbirdVayuz** [comment]
This is done
