### ISSUE TITLE
group details/listing not working

### ISSUE THREAD

**Issue by MaroofTech** [Bitovn-Micro-Services/groups-issues#271]
![Screenshot from 2023-10-04 18-21-31](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78342064/06e4aabe-9206-43f8-a382-e263dd713332)
![Screenshot from 2023-10-04 18-24-02](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78342064/1834200d-4bf2-49b0-ad9c-4e8d68661080)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Bitovn-Micro-Services/groups-issues/assets/128778447/1fc3387d-56ef-4b10-91e1-65dd22c7dc88)
Same issue here, It keeps loading.

**Comment by technicalbirdVayuz** [comment]
@vinayak-vayuz @MaroofTech Please check this in Private.

Let me know if issue persists

**Comment by MaroofTech** [comment]
@technicalbirdVayuz working in Private
