### ISSUE TITLE
Configuration of Public Flow

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#30]

**Comment by technicalbirdVayuz** [comment]
Moving this to Build 2, as Public Group configuration also required here

**Comment by technicalbirdVayuz** [comment]
Including Public Flow also

**Comment by technicalbirdVayuz** [comment]
Update; public flow is configured. Need to configure count in tabs

**Comment by technicalbirdVayuz** [comment]
Group details > Invite members via dropdown not showing up
