### ISSUE TITLE
Topic details > Reply in comments giving error "Something went wrong!"

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#34]
![2022-09-06_163734](https://user-images.githubusercontent.com/78781245/188621000-44fb2845-8465-49c1-8b4e-f55c7ef0aaf4.png)

**Comment by technicalbirdVayuz** [comment]
It could be because you didn't enable token & ids. Please check again by opening group via social, its should work
