### ISSUE TITLE
Request UI is breaking, getting out of the page

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn-Micro-Services/groups-issues#340]

**Comment by technicalbirdVayuz** [comment]
Scroll on sub header is not working

**Comment by bidyut-majumdar** [comment]
![Screenshot_20231023_152643](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78781245/c88b8414-5878-4430-8bfd-e9213484edab)

scrolling on 2nd nav bar not working, so request tab is not accesssible.
