### ISSUE TITLE
In detail page, data needs to be shared in better way.

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn-Micro-Services/groups-issues#341]
Member text is not aligned

**Comment by bidyut-majumdar** [comment]
![Uploading Screenshot_20231023_152643.jpg…]()

**Comment by bidyut-majumdar** [comment]
![Screenshot_20231023_152643](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78781245/ddd879d0-06d9-4528-a8d0-6b72945058eb)
