### ISSUE TITLE
Fresh login to social > Getting Forbidden toast message with loading screen

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#342]
![Screenshot 2023-10-25 083853](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78781245/371dd33a-2574-4a92-8c6f-d6f3b555ff2e)

**Comment by technicalbirdVayuz** [comment]
Discussed today, there was issue with hardcoded value, fixed
