### ISSUE TITLE
Getting "Invalid JSON response" when trying to switch theme

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#343]
![2](https://github.com/Bitovn-Micro-Services/groups-issues/assets/78781245/5d6402df-aed0-4db0-90b5-628981a5d30f)

**Comment by technicalbirdVayuz** [comment]
Moved to social issue tracker

**Comment by technicalbirdVayuz** [comment]
https://github.com/manojnegi07/social-external/issues/1346
