### ISSUE TITLE
Group overall > Wherever comments exists or topics > Lottie reactions

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#35]

**Comment by technicalbirdVayuz** [comment]
Are you referring to multiple reactions?

**Comment by bidyut-majumdar** [comment]
Yes, I have assigned this to myself.

Reactions in the comments/threads etc. Once I get confirmation from Tej sir I will let you know if we can proceed with this, may be considered for upcoming build.

**Comment by technicalbirdVayuz** [comment]
@bidyut-majumdar  This is in your next week agenda (Sept 19-23)

**Comment by bidyut-majumdar** [comment]
Yes
