### ISSUE TITLE
Network invite modal > Please make sure after search upon clicking the cross button it turns back to search icon

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn-Micro-Services/groups-issues#37]
Please make sure after searching upon clicking the cross button then it clears the search result and shows all members listing, it should also turn back to the previous search icon:

![2022-09-06_205022](https://user-images.githubusercontent.com/78781245/188673743-af3d0dc4-d89a-4192-ac1c-efe620713810.png)

**Comment by technicalbirdVayuz** [comment]
@bidyut-majumdar Check if you could increase the size of padding the cross icon, one have to click exactly on icon to clear the results
