### ISSUE TITLE
Create group >> Upload banner

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#41]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/188858334-87c34a29-6fdd-4e35-ad0d-437cf76e6d01.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/85341053/188858524-439efc9b-26e1-41b2-b1b4-838a52c9db73.png">

**Comment by technicalbirdVayuz** [comment]
We need to change cropper then

**Comment by technicalbirdVayuz** [comment]
#5

**Comment by technicalbirdVayuz** [comment]
Will configure this in the end
