### ISSUE TITLE
Detail >> There is no difference in the group name and desciption in terms of UI please fix

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#46]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/85341053/188860463-1b32cb35-8fb0-4b67-bebe-1759ff732cf0.png">

**Comment by bidyut-majumdar** [comment]
Group name and description have already different text styles, the screenshot above contains only the description part.

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar Please highlight Group name.

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar About group title not highlighted 
![image](https://user-images.githubusercontent.com/109590553/221797180-e7d565c2-7348-40fe-bae3-9c8bc7128c63.png)
