### ISSUE TITLE
Create topic >> This UI structure doesnot make sense for the presnt UI please remove it the hole structure is breaking right now

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#49]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/85341053/188861019-70387a10-7ae1-4d34-8959-55fd86b13b17.png">

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz please add max character limit to 150 , no dot dot , but while creating topic it should be limited to 150 character length .

**Comment by technicalbirdVayuz** [comment]
Limitation Added in Create Topic

**Comment by technicalbirdVayuz** [comment]
Limitation added in Create Group

**Comment by technicalbirdVayuz** [comment]
Configured in Topic Detail also

**Comment by technicalbirdVayuz** [comment]
@bidyut-majumdar  It is coming like this now, 

![image](https://user-images.githubusercontent.com/18699624/189299678-a53f2e6c-17f1-4d44-9846-94ce21537ebc.png)


Please make it look good. Also, Following are the limits
- Groups Name  & Topic Name - 150 (While Creation)
- Group Description & Topic Description - 800 (While Creation)
- While Showing on the card, limit is configurable from the HTML too., current limit is for 150 for group name & topic name & 100 for description
