### ISSUE TITLE
Create topic >> Remove this icon as it does not make sense here 

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#51]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/85341053/188861532-b57d0e32-1673-4190-883f-d65620277254.png">

**Comment by bidyut-majumdar** [comment]
Several other options in the chatbox would appear on the same box, so it will appear valid at that point, so I have kept it like this ,

**Comment by bidyut-majumdar** [comment]
The doubt about image fit issue was not here , so no actionable on this for now .
