### ISSUE TITLE
Create topic >> Please give a editor here also need the option to add image

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#53]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/85341053/188863548-38926019-bd11-459e-a94c-423695c9a782.png">

**Comment by technicalbirdVayuz** [comment]
Editor will be configured in Upcoming Build

**Comment by technicalbirdVayuz** [comment]
Video, poll on the create discussion

**Comment by technicalbirdVayuz** [comment]
Editor configured, UAT required
