### ISSUE TITLE
Topic listing >> UI is not organised, add read more and less and make it more like a feed structure add limit of character where required

### ISSUE THREAD

**Issue by rgnarok** [Bitovn-Micro-Services/groups-issues#56]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/85341053/188864778-39b2eed4-ff40-488d-81ff-8458a6c8467c.png">

**Comment by technicalbirdVayuz** [comment]
#22

**Comment by technicalbirdVayuz** [comment]
@bidyut-majumdar Group Detail page still have some issues when the text is more, it breaks the UI. Currently limit is added, once that is fixed. Read more & Read less can be added

**Comment by bidyut-majumdar** [comment]
As we discussed today, read more / read less is not required currently. Once new editor comes further approach will be taken accordingly.
