### ISSUE TITLE
3 dots needs to be aligned to the right

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn-Micro-Services/groups-issues#69]
![image](https://user-images.githubusercontent.com/18699624/189286089-58a350b1-0cbe-4c7a-ba3b-2bbff67c4873.png)

Please check the issue, it was working fine in Blaze @bidyut-majumdar

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz fixed , code pushed
